# Generated by Django 3.2.13 on 2023-05-05 14:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='type_voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='voiture',
            fields=[
                ('immatriculation', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=10)),
                ('couleur', models.CharField(max_length=10)),
                ('dispo', models.BooleanField(default=True)),
                ('prix_journalier', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('type_carburant', models.CharField(default='Gasoil', max_length=10)),
                ('etat_carburant', models.FloatField(default=0)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcvoitures.marque')),
                ('type_voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcvoitures.type_voiture')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('remaqrques', models.CharField(max_length=200)),
                ('etat', models.CharField(default='En cours', max_length=20)),
                ('ditance_parcourut', models.FloatField(default=0, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiture', to='lcvoitures.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='photo_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcvoitures.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire', models.FloatField(max_length=2)),
                ('date_embauche', models.DateField(default=datetime.date(2023, 5, 5))),
                ('situation', models.CharField(default='en cours', max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
